Added mustek_usb backend which supports the Mustek BearPaw 2448 TA Pro. Changes of the code before inclusion to CVS can be found in doc/mustek_usb2/mustek_usb2.CHANGES.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5944,7 +5944,6 @@ if test "${enable_fork_process+set}" = set; then
       fi
 
 fi;
-  if test $use_pthread = yes ; then
 
 for ac_header in pthread.h
 do
@@ -6263,7 +6262,7 @@ if test `eval echo '${'$as_ac_var'}'` = yes; then
   cat >>confdefs.h <<_ACEOF
 #define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
 _ACEOF
-
+ have_pthread=yes
 else
   use_pthread=no
 fi
@@ -6274,13 +6273,15 @@ fi
 
 done
 
-  fi
+
   if test $use_pthread = yes ; then
 
 cat >>confdefs.h <<_ACEOF
 #define USE_PTHREAD "$use_pthread"
 _ACEOF
 
+  fi
+  if test "$have_pthread" = "yes" ; then
     CPPFLAGS="${CPPFLAGS} -D_REENTRANT"
   fi
   echo "$as_me:$LINENO: checking whether to enable pthread support" >&5
@@ -10846,7 +10847,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 10849 "configure"' > conftest.$ac_ext
+  echo '#line 10850 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -12079,7 +12080,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:12082:" \
+echo "$as_me:12083:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -13179,11 +13180,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13182: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13183: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13186: \$? = $ac_status" >&5
+   echo "$as_me:13187: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13441,11 +13442,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13444: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13445: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13448: \$? = $ac_status" >&5
+   echo "$as_me:13449: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13503,11 +13504,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13506: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13507: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13510: \$? = $ac_status" >&5
+   echo "$as_me:13511: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15734,7 +15735,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 15737 "configure"
+#line 15738 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -15832,7 +15833,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 15835 "configure"
+#line 15836 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18082,11 +18083,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18085: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18086: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18089: \$? = $ac_status" >&5
+   echo "$as_me:18090: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18144,11 +18145,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18147: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18148: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18151: \$? = $ac_status" >&5
+   echo "$as_me:18152: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19506,7 +19507,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 19509 "configure"
+#line 19510 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19604,7 +19605,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 19607 "configure"
+#line 19608 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -20489,11 +20490,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:20492: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20493: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:20496: \$? = $ac_status" >&5
+   echo "$as_me:20497: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -20551,11 +20552,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:20554: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20555: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:20558: \$? = $ac_status" >&5
+   echo "$as_me:20559: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22675,11 +22676,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:22678: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:22679: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:22682: \$? = $ac_status" >&5
+   echo "$as_me:22683: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -22937,11 +22938,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:22940: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:22941: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:22944: \$? = $ac_status" >&5
+   echo "$as_me:22945: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -22999,11 +23000,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:23002: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:23003: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:23006: \$? = $ac_status" >&5
+   echo "$as_me:23007: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -25230,7 +25231,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 25233 "configure"
+#line 25234 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -25328,7 +25329,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 25331 "configure"
+#line 25332 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -26480,6 +26481,12 @@ echo "$as_me: Manually selected backends: ${BACKENDS}" >&6;}
     echo "*** disabling net backend (sys/socket.h not found)"
   else
     BACKENDS="${BACKENDS} net"
+  fi
+
+  if test "${have_pthread}" != "yes"; then
+    echo "*** disabling MUSTEK_USB2 backend (failed to find pthread library)"
+  else
+    BACKENDS="${BACKENDS} mustek_usb2"
   fi
 
   # Check whether --enable-pnm-backend or --disable-pnm-backend was given.
