Added support for IPv6. Updated manpages. Patch from Julien BLACHE <jb@jblache.org>.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1011,6 +1011,8 @@ Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --enable-warnings       turn on tons of compiler warnings (GCC only)
+  --enable-ipv6           enable IPv6 (with IPv4) support
+  --disable-ipv6          disable IPv6 support
   --enable-static=PKGS  build static libraries default=no
   --enable-shared=PKGS  build shared libraries default=yes
   --enable-fast-install=PKGS  optimize for fast installation default=yes
@@ -8013,9 +8015,12 @@ rm -f conftest.mmap
 
 
 
+
+
 for ac_func in atexit inet_addr inet_aton inet_ntoa ioperm mkdir \
     scsireq_enter strftime strstr strtod  \
-    cfmakeraw tcsendbreak strcasecmp strncasecmp _portaccess
+    cfmakeraw tcsendbreak strcasecmp strncasecmp _portaccess \
+    getaddrinfo getnameinfo
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $ac_func" >&5
@@ -8296,6 +8301,90 @@ cat >>confdefs.h <<\_ACEOF
 #define DISABLE_LINUX_SG_IO 1
 _ACEOF
 
+fi
+
+if test "$ac_cv_func_getnameinfo" = "yes" && test "$ac_cv_func_getaddrinfo" = "yes" ; then
+
+echo "$as_me:$LINENO: checking whether to enable IPv6" >&5
+echo $ECHO_N "checking whether to enable IPv6... $ECHO_C" >&6
+# Check whether --enable-ipv6 or --disable-ipv6 was given.
+if test "${enable_ipv6+set}" = set; then
+  enableval="$enable_ipv6"
+   case "$enableval" in
+  no)
+       echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+       ipv6=no
+       ;;
+  *)   echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define ENABLE_IPV6 1
+_ACEOF
+
+       ipv6=yes
+       ;;
+  esac
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+	#define INET6
+	#include <sys/types.h>
+	#include <sys/socket.h>
+int
+main ()
+{
+
+	 /* AF_INET6 available check */
+ 	if (socket(AF_INET6, SOCK_STREAM, 0) < 0)
+   	  exit(1);
+ 	else
+   	  exit(0);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define ENABLE_IPV6 1
+_ACEOF
+
+  ipv6=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  ipv6=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi;
+
+else
+  ipv6="no"
 fi
 
 
@@ -9475,7 +9564,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 9478 "configure"' > conftest.$ac_ext
+  echo '#line 9567 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -10004,7 +10093,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:10007: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:10096: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -11836,7 +11925,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11839 "configure"
+#line 11928 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11934,7 +12023,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11937 "configure"
+#line 12026 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14026,6 +14115,8 @@ echo "Configuration: `eval eval echo ${sysconfdir}`"
 echo "Libraries:     `eval eval echo ${libdir}`"
 echo "Binaries:      `eval eval echo ${bindir}` and `eval eval echo ${sbindir}`"
 echo "Manpages:      `eval eval echo ${mandir}`"
+echo "Network parameters:"
+echo "IPv6 support:  `eval eval echo ${ipv6}`"
 
 if test "$SANE_CONFIG_PATH" != "no" ; then
   SANE_INSTALLED_VERSION=`$SANE_CONFIG_PATH --version`
